remote_theme: just-the-docs/just-the-docs
title: Stage informatique
description: Ceci est le site GitHub Pages décrivant mon stage en informatique
plugins:
  - jekyll-remote-theme
color_scheme: dark
footer_content: Made by Jun-Oh